photologue/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'photologue'
urlpatterns = [
    path('', TemplateView.as_view(template_name="photologue/home.html"), name='home'),
    path('database/', views.database_list_view, name='database_list'),
    path('database/create/', views.database_create_view, name='database_create'),
    path('database/<slug:slug>/', views.database_detail_view, name='database_detail'),
    path('database/<slug:slug>/edit/', views.database_edit_view, name='database_edit'),

    path('index/', views.database_index_list_view, name='database_index_list'),

    # Info about indexes for concrete database. If no database parameter provided then show list of databases
    # parameter ?database=slug
    path('index/info/', views.database_index_info_view, name='database_index_info'),

    # Form to create new index for some database without deleting old ones.
    # Must provide option whether to use new index as default.
    # parameter ?database=slug
    path('index/create/', views.database_index_create_view, name='database_index_create'),

    # Info about concrete index: which database, how many objects indexed,
    # list of events which used this index...
    path('index/<slug:slug>/', views.database_index_detail_view, name='database_index_detail'),

    path('event/', views.event_list_view, name='event_list'),
    path('event/create/', views.event_create_view, name='event_create'),
    path('event/<slug:slug>/', views.event_detail_view, name='event_detail'),
    path('event_by_id/<int:id>/', views.event_detail_by_id_view, name='event_detail_by_id'),

    path('database/<slug:database_slug>/photo/<int:pk>/', views.database_photo_detail_view, name='database_photo_detail'),
    path('event/<slug:event_slug>/photo/<int:pk>/', views.event_photo_detail_view, name='event_photo_detail'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('photologue/', include('photologue.urls')),
                  path('', RedirectView.as_view(pattern_name='photologue:home'), name='go_to_photologue_home'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}css/screen.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}css/cropper.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{ STATIC_URL }}js/html5shiv.min.js"></script>
    <script src="{{ STATIC_URL }}js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
            <li class="home"><a href="/">Home</a></li>
            <li class="home"><a href="{% url 'photologue:database_list' %}">Databases</a></li>
            <!--<li class="home"><a href="{% url 'photologue:event_list' %}">Events</a></li>-->
            <!--<li class="home"><a href="{% url 'photologue:database_index_list' %}">Indexed</a></li>-->
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{{ STATIC_URL }}js/jquery-3.1.1.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/project.js"></script>
<script src="{{ STATIC_URL }}js/cropper.min.js"></script>
    {% block javascript %}
    {% endblock %}

<script>
function OnSubmitFormEventBasket()
{
  console.log("here")
  select_field = document.doform.event_basket
  event_id = select_field.options[select_field.selectedIndex].value
  new_action = "/photologue/event_by_id/" + event_id + "/"
  document.doform.action = new_action
  return true;
}

</script>

</body>
</html>