photologue/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'photologue'
urlpatterns = [
    path('', TemplateView.as_view(template_name="photologue/home.html"), name='home'),
    path('database/', views.database_list_view, name='database_list'),
    path('database/create/', views.database_create_view, name='database_create'),
    path('database/<slug:slug>/', views.database_detail_view, name='database_detail'),
    path('database/<slug:slug>/edit/', views.database_edit_view, name='database_edit'),

    path('index/', views.database_index_list_view, name='database_index_list'),

    # Info about indexes for concrete database. If no database parameter provided then show list of databases
    # parameter ?database=slug
    path('index/info/', views.database_index_info_view, name='database_index_info'),

    # Form to create new index for some database without deleting old ones.
    # Must provide option whether to use new index as default.
    # parameter ?database=slug
    path('index/create/', views.database_index_create_view, name='database_index_create'),

    # Info about concrete index: which database, how many objects indexed,
    # list of events which used this index...
    path('index/<slug:slug>/', views.database_index_detail_view, name='database_index_detail'),

    path('event/', views.event_list_view, name='event_list'),
    path('event/create/', views.event_create_view, name='event_create'),
    path('event/<slug:slug>/', views.event_detail_view, name='event_detail'),
    path('event_by_id/<int:id>/', views.event_detail_by_id_view, name='event_detail_by_id'),

    path('database/<slug:database_slug>/photo/<int:pk>/', views.database_photo_detail_view, name='database_photo_detail'),
    path('event/<slug:event_slug>/photo/<int:pk>/', views.event_photo_detail_view, name='event_photo_detail'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('photologue/', include('photologue.urls')),
                  path('', RedirectView.as_view(pattern_name='photologue:home'), name='go_to_photologue_home'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photologue/forms.py
import zipfile
from zipfile import BadZipFile

from PIL import Image
from django import forms
from django.forms import ModelForm

from .models import (Database,
                     Event,
                     DatabasePhoto,
                     CBIRIndex,
                     EventPhoto)

FILE_MAX_LENGTH = 100

file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class DatabaseForm(ModelForm):
    photos = forms.ImageField(required=False,
                              label='photos',
                              widget=forms.ClearableFileInput(attrs={'multiple': True}))
    zip_file = forms.FileField(required=False)

    class Meta:
        model = Database
        fields = ['date_added', 'title', 'slug', 'description', 'cbir_index_default']

    def __init__(self, *args, **kwargs):
        my_params = kwargs.pop('my_params', {})
        my_mode = my_params.get('my_mode')

        super().__init__(*args, **kwargs)

        if my_mode == 'edit':
            self.fields.pop('slug')
        elif my_mode == 'create':
            self.fields.pop('cbir_index_default')

    def clean_zip_file(self):
        """Open the zip file a first time, to check that it is a valid zip archive.
        We'll open it again in a moment, so we have some duplication, but let's focus
        on keeping the code easier to read!
        """
        zip_file = self.cleaned_data['zip_file']
        if not zip_file:
            return zip_file
        try:
            zip = zipfile.ZipFile(zip_file)
        except BadZipFile as e:
            raise forms.ValidationError(str(e))
        bad_file = zip.testzip()
        if bad_file:
            zip.close()
            raise forms.ValidationError('"%s" in the .zip archive is corrupt.' % bad_file)
        zip.close()  # Close file in all cases.
        return zip_file

    def clean(self):
        cleaned_data = super().clean()

        cbir_index_default = cleaned_data.get('cbir_index_default')
        if cbir_index_default:
            database = self.instance
            if cbir_index_default.database != database:
                self.add_error('cbir_index_default', f'Chosen cbir_index {cbir_index_default} corresponds to another database')


class EventForm(ModelForm):
    query_photos = forms.ImageField(required=False,
                                    label='query photos',
                                    widget=forms.ClearableFileInput())
    # query_photo_from_database = forms.ModelChoiceField(DatabasePhoto.objects.all(),
    #                                                             required=False,
    #                                                             label='query photos from database')
    qe = forms.BooleanField(required=False, initial=False, label='qe',
                            help_text='Query expansion')
    sv = forms.BooleanField(required=False, initial=False, label='sv',
                            help_text='Rerank by spatial verification')
    topk = forms.IntegerField(required=False, initial=10, label='topk',
                              help_text='Maximum count resulting photos')

    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Event
        fields = ['date_added', 'title', 'slug', 'description', 'database', 'cbir_index']
        widgets = {
            'query_photos': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    def clean(self):
        cleaned_data = super().clean()
        database = cleaned_data.get('database')

        if database:
            cleaned_data['cbir_index'] = cleaned_data['cbir_index'] or database.cbir_index_default
            cbir_index = cleaned_data['cbir_index']

            if not cbir_index:
                self.add_error('cbir_index', f'There are no indexes for database {database}. Firstly, create index.')
            elif cbir_index.database != database:
                self.add_error('cbir_index', f'Chosen cbir_index {cbir_index} corresponds to another database')

        return cleaned_data



class CbirIndexForm(ModelForm):
    set_as_default = forms.BooleanField(required=False,
                                        initial=False, )
    des_type = forms.ChoiceField(
        choices=(
            ('HardNetAll', 'HardNetAll'),
            ('l2net', 'l2net'),
            ('sift', 'sift'),
            (None, 'default')
        ),
        required=False
    )

    class Meta:
        model = CBIRIndex
        fields = ['date_added', 'title', 'slug', 'name', 'description', 'database']

photologue/views.py
import logging
import os
import zipfile
from io import BytesIO
from pathlib import Path

from PIL import Image
from django.contrib import messages
from django.core.files.base import ContentFile
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from tqdm import tqdm

from . import forms
from . import models


logger = logging.getLogger('photologue.views')

PAGINATE_PHOTOS_BY = 50


class DatabaseListView(ListView):
    model = models.Database
    template_name = 'photologue/database_list.html'
    paginate_by = 20


database_list_view = DatabaseListView.as_view()


class DatabaseDetailView(DetailView):
    model = models.Database
    template_name = 'photologue/database_detail.html'
    context_object_name = 'database'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['events'] = context['database'].get_events(limit=None)
        photos = models.DatabasePhoto.objects.filter(database=self.get_object())

        paginator = Paginator(photos, PAGINATE_PHOTOS_BY)
        page = self.request.GET.get('page')
        photos_to_give = None
        try:
            photos_to_give = paginator.page(page)
        except PageNotAnInteger:
            photos_to_give = paginator.page(1)
        except EmptyPage:
            photos_to_give = paginator.page(paginator.num_pages)

        context['photos_to_give'] = photos_to_give
        return context


database_detail_view = DatabaseDetailView.as_view()


def database_create_view(request):
    context = {}

    if request.method == 'POST':
        form = forms.DatabaseForm(request.POST, request.FILES, my_params={'my_mode': 'create'})
        if form.is_valid():
            database = form.save(commit=False)
            database.count = 0
            database.save()
            total_count_files = 0

            zip_file = form.cleaned_data['zip_file']
            if zip_file:
                # Handling files from zip
                logger.info('Handling files from zip archive')
                zip = zipfile.ZipFile(zip_file)
                for filename in tqdm(sorted(zip.namelist())):
                    # logger.debug('Reading file "{0}".'.format(filename))

                    if filename.startswith('__') or filename.startswith('.'):
                        logger.debug('Ignoring file "{0}".'.format(filename))
                        continue
                    if os.path.dirname(filename):
                        logger.warning('Ignoring file "{0}" as it is in a subfolder; all images should be in the top '
                                       'folder of the zip.'.format(filename))
                        continue

                    data = zip.read(filename)

                    if not len(data):
                        logger.debug('File "{0}" is empty.'.format(filename))
                        continue

                    # Basic check that we have a valid image.
                    try:
                        file = BytesIO(data)
                        opened = Image.open(file)
                        opened.verify()
                    except Exception:
                        # Pillow doesn't recognize it as an image.
                        # If a "bad" file is found we just skip it.
                        logger.error('Could not process file "{0}" in the .zip archive.'.format(
                            filename))
                        if request:
                            messages.warning(request,
                                             'Could not process file "{0}" in the .zip archive.'
                                             .format(filename),
                                             fail_silently=True)
                        continue

                    database_photo = models.DatabasePhoto(database=database)
                    contentfile = ContentFile(data)
                    database_photo.image.save(filename, contentfile)
                    database_photo.name = Path(database_photo.image.name).name
                    database_photo.save()
                    total_count_files += 1

                zip.close()

                if request:
                    messages.success(request,
                                     'The photos from zip have been added.',
                                     fail_silently=True)

            # Handling files
            logger.info('Handling files')
            for file_image in tqdm(request.FILES.getlist('photos')):
                database_photo = models.DatabasePhoto(database=database,
                                                      image=file_image)
                database_photo.save_when_name_not_inited()
                total_count_files += 1

            database.count = total_count_files
            database.save()
            return HttpResponseRedirect(reverse('photologue:database_detail', kwargs={'slug': database.slug}))
    else:
        form = forms.DatabaseForm(my_params={'my_mode': 'create'})

    context['form'] = form
    return render(request, 'photologue/database_create.html', context)


def database_edit_view(request, slug):
    context = {}
    database = get_object_or_404(models.Database, slug=slug)
    logger = logging.getLogger('photologue.database.edit')

    if request.method == 'POST':
        form = forms.DatabaseForm(request.POST, request.FILES, instance=database, my_params={'my_mode': 'edit'})
        if form.is_valid():
            database = form.save(commit=False)

            count_new_photos = 0
            for file_image in request.FILES.getlist('photos'):
                database_photo = models.DatabasePhoto(database=database,
                                                      image=file_image)
                database_photo.save_when_name_not_inited()
                count_new_photos += 1

            database.count = database.count + count_new_photos
            database.save()
            return HttpResponseRedirect(reverse('photologue:database_detail', kwargs={'slug': database.slug}))
    else:
        logger.info('GET')
        form = forms.DatabaseForm(instance=database, my_params={'my_mode': 'edit'})

    context['form'] = form
    context['database'] = database
    return render(request, 'photologue/database_edit.html', context)


def event_detail_by_id_view(request, id):
    event = get_object_or_404(models.Event, id=id)
    return event_detail_view(request, slug=event.slug)


def event_detail_view(request, slug):
    context = {}
    event = get_object_or_404(models.Event, slug=slug)
    context['event'] = event
    event_status = event.status  # ['search', 'basket', 'ready']

    if request.method == 'POST':
        dos = ['add', 'remove', 'commit']
        do = request.POST.get('do')

        if event.status == 'basket':
            if do == 'add':
                database_photos_to_add = None
                if request.POST.get('toggle_all'):
                    found_photos = event.get_found_photos()
                    database_photos_to_add = [found_photo.database_photo for found_photo in found_photos]
                else:
                    database_photos_to_add = [get_object_or_404(models.DatabasePhoto, id=photo_id)
                                              for photo_id
                                              in request.POST.getlist('chosen_photo')]
                for database_photo in database_photos_to_add:
                    event_basket_chosen_photo = models.EventBasketChosenPhoto(
                        description=database_photo.description or str(database_photo),
                        event=event,
                        database_photo=database_photo)
                    try:
                        event_basket_chosen_photo.save()
                    except IntegrityError:
                        logger.warning('Supressed integirty Error')
                return HttpResponseRedirect(reverse('photologue:event_detail', kwargs={'slug': event.slug}))
            elif do == 'commit':
                descriptions = request.POST.getlist('description')
                chosen_photos = models.EventBasketChosenPhoto.objects.filter(event=event)
                # print(f'len(descriptions): {len(descriptions)}, len(chosen_photos): {len(chosen_photos)}')
                # print(f'AAA descriptions: {descriptions}')
                # print(f'AAA chosen_photos: {chosen_photos}')
                while len(descriptions) < len(chosen_photos):
                    descriptions += [chosen_photos[len(descriptions)].description]
                # print(f'AAA descriptions: {descriptions}')
                for index_chosen_photo, chosen_photo in enumerate(chosen_photos):
                    event_photo = models.EventPhoto(
                        description=descriptions[index_chosen_photo],
                        is_query=False,
                        event=event,
                        database_photo=chosen_photo.database_photo)
                    event_photo.save()
                event.status = 'ready'
                event.save()
                return HttpResponseRedirect(reverse('photologue:event_detail', kwargs={'slug': event.slug}))
            else:
                return HttpResponseBadRequest(f'Bad do `{do}`. Must be one of {dos}')
        else:
            # event.status != 'basket'
            return HttpResponseBadRequest(f'Bad status: {event.status}. Must be `basket`')
    else:
        # request.method != 'POST'
        if event_status == 'search':
            context['query_photos'] = event.get_query_photos()
            return render(request, 'photologue/event_detail_search.html', context)
        elif event_status == 'basket':

photologue/templates/photologue/database_detail.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{{ database.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h2 class="page-header">{{ database.title }}</h2>
    <p class="muted">
        <small>{% trans "Published" %} {{ database.date_added }}</small>
    </p>
    <h4>Description</h4>
    <p style="text-indent: 3%">
        {% if database.description %}
        {{ database.description }}
        {% else %}
        --
        {% endif %}
    </p>

    <h4>Count photos</h4>
    <p style="text-indent: 3%">{{database.count}}

    <h4>Default CBIR Index</h4>
    <p style="text-indent: 3%">
        {% if database.cbir_index_default %}
        <a href="{% url 'photologue:database_index_detail' database.cbir_index_default.slug %}">
        {{database.cbir_index_default}}
        </a>
        {% else %}
        --
        {% endif %}
    </p>

    <h4>
        <a href="{% url 'photologue:database_edit' database.slug %}">
            Edit database
        </a>
    </h4>

    <h4>
        <a href="{% url 'photologue:database_index_create'%}?database={{ database.slug }}">
            Create new index for database
        </a>
    </h4>

    <h4>
        <a href="{% url 'photologue:database_index_info'%}?database={{ database.slug }}">
            Indexes info
        </a>
    </h4>

    <h4>
        <a href="{% url 'photologue:event_create' %}?database={{database.slug}}">
            Create new event
        </a>
    </h4>

    <h4>Events</h4>
    <ul>
        {% if events %}
        {% for event in events %}
        <li>
            <a href="{{ event.get_absolute_url }}">
                {{ event.title }}
            </a>
        </li>

        {% endfor %}
        {% else %}
        --
        {% endif %}
    </ul>

    <h4>Photos</h4>
    <ul>
        <div class="row col-lg-12">
        {% for photo in photos_to_give %}
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
            </a>
        {% endfor %}
        </div>

        {% if photos_to_give.has_other_pages %}
  <ul class="pagination">
    {% if photos_to_give.has_previous %}
      <li><a href="?page={{ photos_to_give.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in photos_to_give.paginator.page_range %}
      {% if photos_to_give.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if photos_to_give.has_next %}
      <li><a href="?page={{ photos_to_give.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>

{% endif %}

    </ul>


    <div><a href="{% url 'photologue:database_list' %}" class="btn btn-default">{% trans "All databases" %}</a></div>
</div>

{% endblock %}

photologue/templates/photologue/database_index_create.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}Create database index{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h1 class="page-header">{% trans "Create new index for database" %} {{ database }}</h1>
</div>

{% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action="">
{% else %}
    <form method="post" action="">
{% endif %}
        {% csrf_token %}
{{ form.as_p }}
        <input type="submit" value="Submit">
</form>

{% endblock content %}

photologue/templates/photologue/database_index_detail.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{{ database_index.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h2 class="page-header">{{ database_index.title }}</h2>
    <p class="muted">
        <small>{% trans "Published" %} {{ database_index.date_added }}</small>
    </p>
    {% if database_index.description %}
    <h4>Description</h4>
    <p style="text-indent: 3%">{{ database_index.description }}</p>
    {% endif %}

    <h4>
        TODO: Statistics about index
    </h4>

    <div><a href="{% url 'photologue:database_index_info' %}?database={{database_index.database.slug}}" class="btn btn-default">
        All database {{ database_index.database }} indexes info </a></div>
</div>

{% endblock %}

photologue/templates/photologue/database_index_detail_being_built.html
{% extends "photologue/database_index_detail_base.html" %}
{% load i18n %}

{% block index_detail_content %}
    <h4>
        Index is not built yet. Wait some time and reload.
    </h4>
{% endblock %}

photologue/templates/photologue/database_index_detail_ready.html
{% extends "photologue/database_index_detail_base.html" %}
{% load i18n %}

{% block index_detail_content %}

<h4>In database:</h4>
<p style="text-indent: 3%">{{ database_index.database.count }}</p>

<h4>Indexed:</h4>
<p style="text-indent: 3%">{{ database_index.count_photos_indexed }}</p>

<h4>In database but not indexed:</h4>
<p style="text-indent: 3%">{{ difference }}</p>

<h4>Used for training from database:</h4>
<p style="text-indent: 3%">{{ database_index.count_photos_for_training_from_database }}</p>

<h4>Used for training external:</h4>
<p style="text-indent: 3%">{{ database_index.count_photos_for_training_external }}</p>


{% endblock %}

photologue/templates/photologue/database_index_info.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{{ database.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h2 class="page-header">{{ database.title }} indexes info</h2>

    {% if cbir_indexes %}
    <ul>
        {% for cbir_index in cbir_indexes %}
        <li>
            <a href="{{ cbir_index.get_absolute_url }}">
                {{ cbir_index }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    No indexes
    {% endif %}

    <div><a href="{% url 'photologue:database_detail' database.slug %}" class="btn btn-default">Database {{ database }}</a></div>
</div>

{% endblock %}

photologue/templates/photologue/database_list.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{% trans "All Databases" %}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h1 class="page-header">{% trans "Databases" %}</h1>
</div>

<h4>
    <a href="{% url 'photologue:database_create' %}">
        Create new database
    </a>
</h4>

{% if object_list %}
{% for database in object_list %}
<div class="row col-lg-12">
    <h2><a href="{{ database.get_absolute_url }}">{{ database.title }}</a></h2>
    <p class="muted">
        <small>{% trans "Published" %} {{ database.date_added }}</small>
    </p>
    {% if database.description %}
    <h4>Description</h4>
    <p style="text-indent: 3%">{{ database.description|safe }}</p>
    {% endif %}

    <h4>Events</h4>
    <ul>
        {% if database.get_events %}
        {% for event in database.get_events %}
        <li>
            <a href="{{ event.get_absolute_url }}">{{ event.title }}</a>
        </li>
        {% endfor %}
        {% else %}
        --
        {% endif %}

    </ul>
</div>
{% endfor %}
{% else %}
<div class="row col-lg-12">{% trans "No databases yet" %}.</div>
{% endif %}

<!--TODO: Research how paginator works-->
<!--include "photologue/includes/paginator.html"-->

{% endblock %}

photologue/templates/photologue/event_create.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}Create event{% endblock %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_query_photos").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h1 class="page-header">{% trans "Create new event" %}</h1>
</div>

<form enctype="multipart/form-data" method="post" id="formUpload">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

photologue/templates/photologue/event_detail.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h1 class="page-header">{{ event.title }}</h1>
    <p class="muted">
        <small>{% trans "Published" %} {{ event.date_added }}</small>
    </p>

    {% if warning_message %}
    <h4> {{ warning_message }}</h4>
    {% endif %}


    {% if event.description %}
    <h4>Description</h4>
    <p style="text-indent: 3%">{{ event.description|safe }}</p>
    {% endif %}

    <h4>Query photos</h4>
    <ul>
        {% if query_photos %}
        {% for query in query_photos %}
        <li>
            <h5>{{ query }}</h5>
            {{ query.description }}

            <p>
                <a href="{{ query.database_photo.get_absolute_url }}">
                    database_photo link
                </a>
            </p>
            <img src="{{ query.get_display_url }}" class="thumbnail" alt="{{ query.title }}">

        </li>
        {% endfor %}
        {% else %}
        No query photos
        {% endif %}
    </ul>

    <h4>Result photos</h4>
    <ul>
        {% if result_photos %}
        {% for photo in result_photos %}
        <li>
            <h5>{{ photo }}</h5>
            <p>Similarity: {{ photo.similarity }}</p>
            {{ photo.description }}

            <p>
                <a href="{{ photo.database_photo.get_absolute_url }}">
                    database_photo
                </a>
            </p>
            <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">

        </li>
        {% endfor %}
        {% else %}
        No result photos
        {% endif %}
    </ul>

    <div><a href="{% url 'photologue:database_detail' event.database.slug %}"
            class="btn btn-default">
        {% trans "View all events in database" %}
        </a>
    </div>
</div>

{% endblock %}

photologue/templates/photologue/event_detail_base.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
    <h1 class="page-header">{{ event.title }}</h1>
    <p class="muted">
        <small>{% trans "Published" %} {{ event.date_added }}</small>
    </p>

    {% if warning_message %}
    <h4> {{ warning_message }}</h4>
    {% endif %}

    <h4>Status</h4>
    <p style="text-indent: 3%">{{event.status|upper}}</p>

    {% if event.description %}
    <h4>Description</h4>
    <p style="text-indent: 3%">{{ event.description|safe }}</p>
    {% endif %}

    <h4>Query photos</h4>
    <ul>
        {% if query_photos %}
        {% for query in query_photos %}
        <li>
            <a href="{{ query.database_photo.get_absolute_url }}">
                <p>{{ query }}</p>
            </a>
            Description: {% if query.description %} {{ query.description|safe }}{% else %}--{% endif %}
            <br>
            <img src="{{ query.get_display_url }}" class="thumbnail" alt="{{ query.title }}">
        </li>
        {% endfor %}
        {% else %}
        No query photos
        {% endif %}
    </ul>

    {% block event_detail_content %}
    {% endblock %}

</div>

{% endblock %}

photologue/templates/photologue/event_detail_being_built.html
{% extends "photologue/base.html" %}
{% load i18n %}

{% block event_detail_content %}
    Search is not finished yet. Wait several seconds and reload.
{% endblock %}